alert("Error! plieas enter a valid password.")
alert("welcome to JS Land...\Happy Coding!")
alert("Welcome to JS Land..")
alert("Happy Coding!\  prevent this page from creating addintion dailogs")
alert("Hello...I can run JS through my web browse`s console")
alert("Rana Tanveer Hassan Cco 116850 ,Sylani Mass IT trening\Thank you for your visit my website")